### ISSUE TITLE
interactive setup?

### ISSUE THREAD

**Issue by pc-dok** [itiligent/Guacamole-Setup#1]
is it possible to let run this script also interactive? because the script is a burner. all is working fine after install. but on gcp i want try to run it interactive, to create a bastion guacamole server. did you think that will work in a manner way?

regards
franco

**Comment by itiligent** [comment]
Hi Fracno,

You can run it both interactively or non interactively.  

1. For interactive prompts, just paste the link on the readme ( wget https://raw.githubusercontent.com/itiligent/Guacamole-Setup/main/1-setup.sh && chmod +x 1-setup.sh && ./1-setup.sh ) into your shell, and let it run following prompts. 

2. For automatic/non interactive, run the setup as above, but EXIT the setup script with ctrl+c at the first prompt. From there you can edit any of the section called "silent setup options" at the start of the setup script as you need to them. Any a variables in the setup script with an actual ="value" will not prompt,  so in the right combination it is possible to deploy many appliances at once with zero touch. 
After making any changes, restart the setup script with ./1-setup.sh. The setup script will only overwrite if you run the above wget link becasue this is bacially a download and run commmand. Running the setup script on your local disk  with 
./1-setup.shwill not overwrite itself.  

The setup script is not a burner, it is moved to the guac setup directory for tidiness and can be run again from there.

NOTE: If you want to modify anything other scripts, you must comment out all the wget download links in the setup script so nothing will get overwritten when you run it - in most cases you should not need to edit anything but the setup as all settings are controlled though the setup script's variables.

I hope that helps!

Dave

**Comment by pc-dok** [comment]
ok, thanks for your answer asap. that helps me a lot. thanks for the great work! franco

**Comment by itiligent** [comment]
BTW I added some clearer instructions on the readme and also added a pause at the start of the setup script to show when to break out and make any edits before re-running.
