### ISSUE TITLE
 Query for use of SSL certificates (Sectigo)

### ISSUE THREAD

**Issue by emiliano-colli** [itiligent/Guacamole-Setup#4]
First of all my apologies for my English. 
Then my thanks for the beautiful work done with the Guacamole installation scripts.
I was using the excellent work of @MysticRyuujin but yours seems even more useful and understandable for my low level of knowledge.

My question is to understand what is the best way to parameterize the 1-setup.sh installation script to be able to use the SSL certificates that I already have and that I have been using with version 1.4 ?

Thank you very much in advance and my congratulations for the impeccable work.
Emiliano.

**Comment by itiligent** [comment]
Hi

There are several missing pieces to your question, 
Are your exisiting SSL certs in use with Guacamole and in OpenSSL? (and are they in use with Guacamole's Tomcat/Apache front end  for https or do you have some other reverse proxy front end ?

Do you want to upgrade your Guacamole 1.4 to 1.51? (if so use upgrade script)

Another option is to add nginx in front of your existing system, if so I would make a quick test system to try out the below ....

3-install-nginx.sh & 4a-install-ssl-self-signed.sh can be made to run standalone to add features to your existing. You only need to a adapt the setup variables in each script (they get these values from the setup menus) You will need to add values at the top of each scropt for  DOWNLOAD_DIR=""  PROXY_SITE=""  TOMCAT_VERSION="" GUAC_URL=""  LOG_LOCATION="" then run it to install nginx. Note: When running the first nginx install script it will overwrite any custom items in your existing  /etc/guacamole/guacd.conf, so back this up if your existing file has anything extra in it. (I might fix this in a later version)
Next, before runnig the 4a SSL creation script as standalone,  you will also need to edit the CERT_COUNTRY, CERT_STATE, CERT_LOCATION, CERT_ORG, CERT_OU & PROXY_SITE values to something abitrary, then run is as sudo -E ./4a-install-ssl-self-signed-nginx.sh proxy-site-dns-name  3650. The script will create new certs, and update the nginx config to use them with HTTPS redirect. You can then simply rename your existing certs to the same name as those your just created and copy/overwrite your existing cert to /etc/nginx/ssl/cert and  existing key file in /etc/nginx/ssl/private 


There's lots of ways to solve what you want, but Im not fully clear on what you are needing to do so I hope the above gives you some ideas.

**Comment by emiliano-colli** [comment]
Thank you very much for such a complete answer.
I am using NGINX as front end in the same virtual machine as a reverse
proxy.
Also I prefer to do a fresh install using your script and make the
minimum necessary changes following your logic.

Thanks again.
Emiliano.

**Comment by itiligent** [comment]
in that case, I would use the backup script to capture your existing database, and restore that backup along with (your existing certs) to the brand new system.

**Comment by itiligent** [comment]
ie restore backup with:
gunzip /path/to/backup/<filename>.gz
mysql -u root -p guacamole_db < /path/to/<decompressed file name>.sql

**Comment by emiliano-colli** [comment]
Excellent, I'll tell you how it went when I finish

**Comment by itiligent** [comment]
One final thing with backup (and sorry to mention if this is obvious) but to use this script on your current system, you will also have to edit the backup script manually and add your own values to: 
MYSQL_HOST=
MYSQL_PORT=
GUAC_USER=
GUAC_PWD=
GUAC_DB=
DB_BACKUP_DIR=
BACKUP_EMAIL=
BACKUP_RETENTION=
 Its all very straightforward.  The 1-setup.sh populates these varibles with the settings you will choose when running the full setup from the start of a new build, but these choices might not be accurate/relevent to your old system.
